# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/cygwin/home/alexandre/plasma/vhdl/plasma_hw/plasma_hw.srcs/sources_1/ip/VGA_PROM_DINO/VGA_PROM_DINO.xci
# IP: The module: 'VGA_PROM_DINO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/cygwin/home/alexandre/plasma/vhdl/plasma_hw/plasma_hw.gen/sources_1/ip/VGA_PROM_DINO/VGA_PROM_DINO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_PROM_DINO'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/cygwin/home/alexandre/plasma/vhdl/plasma_hw/plasma_hw.srcs/sources_1/ip/VGA_PROM_DINO/VGA_PROM_DINO.xci
# IP: The module: 'VGA_PROM_DINO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/cygwin/home/alexandre/plasma/vhdl/plasma_hw/plasma_hw.gen/sources_1/ip/VGA_PROM_DINO/VGA_PROM_DINO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_PROM_DINO'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
